version: "3.9"
services:
  # Node.js
  nodejs:
    image: node:20
    container_name: nodejs-service
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${NODE_PORT:-3000}:${NODE_PORT:-3000}"
    depends_on:
      - redis
    command: sh -c "npm install && npm run start:dev"
    environment:
      - NODE_PORT=${NODE_PORT:-3000}
      - APP_ENV=${APP_ENV:-production}
      - APP_NAME=${APP_NAME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - JWT_SECRET=${JWT_SECRET}
      - DB_PATH=${DB_PATH:-database.db}

  # Redis
  redis:
    image: redis:latest
    container_name: redis-queue
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    environment:
      - REDIS_PORT=${REDIS_PORT:-6379}

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - nodejs
